Repository pennlabs/pcr, pull requests merged in 2020-03, with the labels that each got.

#294 Rework DetailsBox
  frontend/package.json
  frontend/src/DetailsBox.js
  frontend/src/InfoBox.js
  frontend/yarn.lock
Labels: code-cleanup, front-end

#293 Make Edit Button More Noticeable
  frontend/public/static/css/base.css
  frontend/public/static/image/selectcol-btn-sub.svg
  frontend/public/static/image/selectcol-btn.svg
  frontend/src/ColumnSelector.js
  frontend/src/ReviewPage.js
  frontend/src/ScoreBox.js
  frontend/src/ScoreTable.js
Labels: front-end

#291 Frontend Files Refactor
  Pipfile.lock
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/InfoPage.js
  frontend/src/components/DetailsBox.js
  frontend/src/components/Footer.js
  frontend/src/components/InfoBox/InfoBoxRatings.js
  frontend/src/components/InfoBox/InfoBoxTags.js
  frontend/src/components/InfoBox/index.js
  frontend/src/components/Navbar.js
  frontend/src/components/ScoreBox.js
  frontend/src/components/SearchBar.js
  frontend/src/components/common/ColumnSelector.js
  frontend/src/components/common/CourseDetails.js
  frontend/src/components/common/ErrorBox.js
  frontend/src/components/common/GoogleAnalytics.js
  frontend/src/components/common/Popover.js
  frontend/src/components/common/ScoreTable.js
  frontend/src/components/common/index.js
  frontend/src/index.js
  frontend/src/pages/AboutPage.js
  frontend/src/pages/AuthPage.js
  frontend/src/pages/CartPage.js
  frontend/src/pages/ErrorPage.js
  frontend/src/pages/FAQPage.js
  frontend/src/pages/ReviewPage.js
  frontend/src/pages/index.js
  frontend/src/pages/withLayout.js
  frontend/src/utils/api.js
  frontend/src/utils/helpers.js
  frontend/yarn.lock
Labels: code-cleanup

#298 Refactor InfoBox into Functional Components (Stars Not Showing Up Fix)
  frontend/src/components/InfoBox/CourseInfo.js
  frontend/src/components/InfoBox/DepartmentInfo.js
  frontend/src/components/InfoBox/InfoBoxTags.js
  frontend/src/components/InfoBox/InfoRatings.js
  frontend/src/components/InfoBox/InstructorInfo.js
  frontend/src/components/InfoBox/index.js
  frontend/src/components/ScoreBox.js
  frontend/src/components/common/ColumnSelector.js
  frontend/src/constants/index.js
  frontend/src/constants/values.js
  frontend/src/pages/CartPage.js
  frontend/src/pages/ReviewPage.js
  frontend/src/utils/helpers.js
Labels: bug, code-cleanup, high-priority

#296 [WIP] Generate Random Professor Placeholder Images
  frontend/public/static/css/base.css
  frontend/public/static/image/prof-1.svg
  frontend/public/static/image/prof-2.svg
  frontend/public/static/image/prof-3.svg
  frontend/public/static/image/prof-4.svg
  frontend/public/static/image/prof-5.svg
  frontend/public/static/image/prof.png
  frontend/public/static/image/prof.svg
  frontend/src/components/DetailsBox.js
  frontend/src/components/common/ScoreTable.js
  frontend/src/constants/routes.js
  frontend/src/pages/ReviewPage.js
Labels: content
